services:
  postgres:
    image: postgres:16
    container_name: trt-postgres
    environment:
      POSTGRES_DB: trt_incidents
      POSTGRES_USER: trt_user
      POSTGRES_PASSWORD: trt_password
    ports:
      - "5432:5432"
    volumes:
      - 20bc503258c361b77de09277d6b146579ffbb04a0027d4432f365805600637fc:/var/lib/postgresql/data

  backend:
    image: trt-backend:latest
    container_name: trt-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/trt_incidents
      SPRING_DATASOURCE_USERNAME: trt_user
      SPRING_DATASOURCE_PASSWORD: trt_password
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      APP_URL: ${APP_URL}
    expose:
      - "8080"

  frontend:
    image: trt-frontend:latest
    container_name: trt-frontend
    depends_on:
      - backend
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    container_name: trt-nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  20bc503258c361b77de09277d6b146579ffbb04a0027d4432f365805600637fc:
    external: true
