spring.application.name=broadcast-incident-management

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/trt_incidents}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:trt_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:trt_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG
